apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
stringData:
    client_id: ENC[AES256_GCM,data:HPG6DzbAw59HMQhdytXH650=,iv:NZQ5U2NRtX/UufAPCcIVk4c2D+OzEGBVvWcugJ0ibP4=,tag:rFJdt+/X8OM4EUh27RelHg==,type:str]
    client_secret: ENC[AES256_GCM,data:HNOQumH743VnnjtY4cwv6fksTv69R3BZUWC469y4YnWJ40wkl0tluGBG0IX7i3n2sE1EVWqZQilJ4J3N/Y3C,iv:j2td9z+xI8ywgaTta+gu7cMsJLulpkUBondq7B5RHXY=,tag:HCiMlZsnnOsmOmsDagiUeQ==,type:str]
sops:
    age:
        - recipient: age1xuyqesapjwt8fhejc8cmtf2d2nwkmf2mqj0h4u0nke48lflc84mq9jsfs4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvd3JLM0tiNlpRdUdPZHhp
            TWJldEcray9SRjltRWJHU2dlRDY0Z3V3SmtjCkN3QWc5L295MUdzUTVvb3ZzQlhW
            TzhwUVZXKzZGbWpLVUdIdjJOcW5qYjgKLS0tIEZna0Z6bGhia1I4b0lZWWVkVzI0
            eXg2OTE4VkQ5TlZqLzFDcFZXaG1Wa1UK/FnxcEeBqx0UUb8cYSM/aymGTZyVUetj
            E5cI+WNvLdlFyhhEAjQGMz5tLwX6pIcSn9xRFIagd/2g86biKOruyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-22T15:56:57Z"
    mac: ENC[AES256_GCM,data:JVrcBJVscL46F8t3IjKPoCAMSaWc6QK2ZN4exKb27RCcdL+TrEFyk7iQePs+gaqDco682HljCZDlSfFEN7FyFh84HJqrGFJ41ffyM/RCBJBPUMsJ8qwwGtDuejl7ZLCCiPm3PpQjwP0wjpVNl7Z3FzCh8DFGaJN2PMWsfLxqARs=,iv:WWgDIqYMW7YwUV/IpSHuOP9VtLWZ/63/UeZrWtZUzeQ=,tag:+lBzJWp258KjNMKv6K5iKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
