apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack
  - snmp-exporter-release.yaml
  - synology-snmp-credentials.yaml
  - blackbox-exporter-release.yaml
