apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie-config
data:
  ALLOW_SIGNUP: "false"
  DB_ENGINE: sqlite
  DEFAULT_GROUP: Home
  DEFAULT_HOUSEHOLD: Family
  LOG_LEVEL: info
  PGID: "1000"
  PUID: "1000"
  TZ: Europe/Amsterdam
