apiVersion: v1
data:
    cloudflare-secret.json: ENC[AES256_GCM,data:ilroortZ44nEN3YGXsrY+6oVl6MqhXGwLiQf11xnt58jBmnil9hcakFQDRcqCvsbYcwQnhp85XfHwMhq/8DCAfVihtTdwo3GSP14BxTUX4xuKsJmENkPNIaivtLuM3AuYa8vMmxpYh8kiLbZf61VGIbbArOrb/FkfVkidn3sY9zb1+Dw2OTN+siF6h9k448auzhBGX/f05FLpOrM4prMZPveGiMcI7obUSgK8Xox2zIiTIprXnLu7FsMCK9H5GuE1+19iYHikgx+lab7q4sOeqaCUK7W9R26tykndw+HL+yal+HdZlAyBaIuikw=,iv:+FowK7F4qAT/43iWjQRKgKdledrh7SrMbAUPuijbm6I=,tag:wdThhfZPv+WR3pBu0AOPzA==,type:str]
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: audiobookshelf
sops:
    age:
        - recipient: age1xuyqesapjwt8fhejc8cmtf2d2nwkmf2mqj0h4u0nke48lflc84mq9jsfs4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NlQ1ZVBxSEZPdHlMbDdS
            ckw0ZXZDQjVyNkpsd0RaTTlvZmZhTDk1L1h3Ck1kYUVhS3pkUjg4dkYzWk5CNmRH
            ZVpHU2R0emQxaVNkY25naEJWUFhSVkEKLS0tIGJxanpFcmlreEFNYk1OQzIxdkdI
            WVBKSk91cFJrVVNkdERBRmZaMWlIc3cK+jd+Ntvx8zuulPdBo5IZwAvlXST06e7v
            4+TxArPWDTd3AxxmNUdPqxA4teXfbk8LELnpAqIk4huZaFzy6OEmeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T13:10:46Z"
    mac: ENC[AES256_GCM,data:cwMx11jKSpU3TyjTHwJ6ccaRDIt7AEe1MjdOPJJFlp8rPceu7ykrSqnnzSHqbwq7UMMaysvgXip0m3wnTIChmGc+Vgk1onUxag9MDmphpVJEt+8jjWeFdG+m8vB1CIrtZnUxW06a8Aba4amks02PwPS6chSbxL2Ws0i7A9wbz2A=,iv:ekpGDVJvCoMFDYmN1nJmoU67evjfOQDPpEOq9231tQk=,tag:bj/UtYWj4na1EC97YyWwYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
