apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-tls-secret.yaml
  - homelab-baseline-rules.yaml
  - homelab-overview-dashboard.yaml
  - homelab-applications-dashboard.yaml
  - homelab-application-probes.yaml
  - homelab-application-probe-rules.yaml
