apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - apps.yaml
  - infrastructure.yaml
  # Monitoring will be enabled after the base app migration path is verified.
  # - monitoring.yaml
