apiVersion: v1
data:
    cloudflare-secret.json: ENC[AES256_GCM,data:2LN4MudD5PQwxmZvZ10uFMk8pxlr8dqDYFGbTlhwM8jy0QOU+f19vK+A4Mr/Zmdq0Pl4eYe1diFFwsLuokm1jeOoUhtFSG/bwZ0azLUVZXJqtQ2swDnapSQYyd47tf1Scoa+ehNFatjzKyVtQ0TiykTWL/9UuUkqgOnV4Il+zVi7OlJK0x2ryK3Z+rSG730NVzRK9xHKR2zwiEcgdjf9fxF36Kviku2kUb5KwsJBOq/jZ+odQD7hhD0/t8UE+5XUMlOpfsnF4yb/zG8QPiWXi4zxYR4j6MBgh7bzyk3NJW9qia76TIe2geF7Y60=,iv:jUj3BQUorVk3ImrnrgTdi9+mhGQCW5wNyHnKFW5p8P4=,tag:In0JbB/wJJFS+VUHrMfpLQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare-secret
    namespace: linkding
sops:
    age:
        - recipient: age1xuyqesapjwt8fhejc8cmtf2d2nwkmf2mqj0h4u0nke48lflc84mq9jsfs4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRm4xaEZPK0JYdFFGcjcv
            SXRpcjVna0NRUVJvOWdsQ0F5MGlHcU9Jb3ljCjFHODAwVjZPNHdUWDRNUVI0WGI5
            UFd5aWZtTVI3RUdWa0piZmlGODc0amMKLS0tIEw0U2Y4aTdNQjhYZmpzS1BUNTc0
            WXFSODNaV0hOZW1KcjZrNWU4NHhDNzgKd1+Emcuggc7HSl6n0JMpGfhb551vCz/6
            onXfWV8usLNuJ1oYqfBBSTqIExhB5X4DVOyRbxjaLJnEld+ldSioGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-21T19:20:18Z"
    mac: ENC[AES256_GCM,data:PoF7qXT/U1+t82KWIA+ExVAMR77Ppkjnw+FAuND6OsnBSLJTqtkVwB7e+vFXvgUyYsQJKNN/vCIo9f0G+JyrrT4Q5PANnxxwYVVEJkjMx4DvHLFoI8pzw/epW56sQrBmhlrVbm3o37FwBYIRfBKlMIfpQg1Ag6IF8P4HTfFO41M=,iv:QMbhFW/cy40NXzeiQso+gjFdP/bt6NwEBsjOlALiPuo=,tag:IiiY20Bo3VutgQFklidIaA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
