apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding
  - backup-cronjob.yaml
  - linkding-container-env-secret.yaml
  - cloudflare.yaml
  - cloudflare-secret.yaml
images:
  - name: sissbruecker/linkding
    newTag: 1.46.1
