apiVersion: v1
data:
    cloudflare-secret.json: ENC[AES256_GCM,data:tzMToESu0oB5/33Rl/v7oLWAOWjKxUr9mUV3gn8GdhCvoh8XxL/vNragWBx9KFDxByDTUjji6oQiDEKHygWAYau1prlzIRZEmzd/zZWWqOJ3RiB7GjIi7lxBh/6x9TQhT1HL3o7tiHh7IfHg57onFZFxXhRjw9pW+Gf2oG9HIVtFizf11FK6yVu88bQrj2Yn4LM7nkrxIyORfOyw43SWsFvnDjTUeRGVppwznvB1WKErjU++JNoGdsuH/4S1diTHH3FuyP1v5O49524Xd9tqpybDPeLE4iBBVAWPm6zZPwshDm/i+vaq7Xibwlg=,iv:vQ2Qvv4/OofhM/c45hNgdNB/HkVtgNtxua14aPZ149Q=,tag:ae9Fvo8pw4DcjaYUwh6cSA==,type:str]
kind: Secret
metadata:
    name: grafana-cloudflare-secret
    namespace: monitoring
sops:
    age:
        - recipient: age1xuyqesapjwt8fhejc8cmtf2d2nwkmf2mqj0h4u0nke48lflc84mq9jsfs4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOem9COE1HaXVOSVFJRk9B
            TTMwMzBQMVVGOVZ6R3Q3dUMvZk9rbWFnNVJRCkcySWxBUzVPbXlpZ2Z5OXVoSnd3
            M0RKallyRVJhUnE0NHBYcVUxcjhqb0UKLS0tIFJySXA3VmU2WnArdThZWWdBTkVk
            SFZmdVlLa0NyQ3hSLzZJZVRCcEJSRk0KuiHyd4WtuzkTZMfrDiYgXWeDmoyfYn1a
            N+lxJaoItVGXS78VMg2CB3bAaQ5vBYSwTKQIfPwRMhXqyGIPcqzbAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T21:04:00Z"
    mac: ENC[AES256_GCM,data:RKNKW0f05VkkRkjO5P7Q3DD3gmwgdbHFcCg+LoId3h9xEmEFFwZhCQQTtkxb+IQ/q3o66OOmeprGOnO9Iqum2KbmjLGlr0XnD/8mB0y+k+p6pPeAvHi3CtmcKMd2AcEpETce5DvySe/jV9+Fm050ruuMm2mOcEcrsfN46nWZeBA=,iv:15tWVYLDanxxp/kWAEVYw9OWZl0HJ9zf7bcqhZDzhes=,tag:GYmp4H+rcCFh4T4juy9tcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
