apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:kEDB8km1TDg80T5bB5Yg2J7SkgtYY9q3DLPGq/bF8+vG/kbjTtMV5TR0vxCznwaZ2ZVjoXVhSfIJB5fL,iv:8tafzArTcHDiJsJ1DS3bSmz+Tw3s7NypRKNNn2nn7AI=,tag:rTeLwhraiSDskXxEvbf3iw==,type:str]
    admin-user: ENC[AES256_GCM,data:+d2mez5KOHA=,iv:2XT5Y/rEtV6vlwCGdbbzymhX7HPeQQE+4GvsWnNKdmw=,tag:ViblWrvWKZe9uDh1zMmKuQ==,type:str]
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
sops:
    age:
        - recipient: age1xuyqesapjwt8fhejc8cmtf2d2nwkmf2mqj0h4u0nke48lflc84mq9jsfs4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbExMWVZOYkRWNkNsQ3Js
            WFAwNWY4WE9TK2kyRk5JdjNST052NUR1ZzJNCnFrSWdVS24wZGM1Q0p4bklEcVFK
            enNldnN3WFJXVnFiWTVNUENVVUJlNjAKLS0tIENtOEZ6ME15dVQvVU5JbUlaWTRp
            NHN1V0l1Tm9MT1c3ek8wTE03bkwwbm8KfKcSGmwJ1eu3rH/eWmjjBCSIvHh6LBEK
            Y8dYywBntEBIZ9LeouqSblHPEwjibBEAJu83uDEw2HUKQMZ+rIA0+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T15:54:38Z"
    mac: ENC[AES256_GCM,data:G9vJJ6jUTR5U67uaB35D0fjayJX3QIllLpIw8Deu0dTuKi7Y42JGWxgjVVjBspA4Wu7E5dZlab1F0ETPGofdkCx8TKkYDPNMRKHPyhhDAZt0EjupCiXLZmebnP9y1sx/S35ssPR8kUKP3HIJRWVRHrCJrEjoMBqAWR5rxPAlec0=,iv:Sf/wc4Sd1tizFF9uQXNp6/v8YDl8m0V0t5BWD19KsF0=,tag:JHm2aYJVh8g7S3H022SdPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
